[[headers]]
  for = "*.js"
  [headers.values]
  Content-Type = "text/javascript"

[build]
  command = "npm run build"
<<<<<<< HEAD
  publish = "dist"
=======
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
>>>>>>> origin/main
